name: CI/CD Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      deploy:
        description: "Развернуть сразу на сервере?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute for gradlew
        run: chmod +x gradlew || true

      - name: Build JAR
        run: ./gradlew clean bootJar -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/kolbasalive/eventservice:latest
            ghcr.io/kolbasalive/eventservice:${{ github.sha }}

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true' }}
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            cd /home/kolbasa/EventService
            git pull origin master || true
            docker-compose -f docker-compose-prod.yaml pull
            docker-compose -f docker-compose-prod.yaml up -d
